source 'https://github.com/CocoaPods/Specs.git'

target 'ABMinimalMenu', :exclusive => true do
  pod "ABMinimalMenu", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ABMinimalMenu", :path => "../"

  
end
